config/routes.rb
MyJournal::Application.routes.draw do
  devise_for :admins, :path => "admin",
    :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'forgot_password' },
    :controllers => { :sessions => "admin/sessions",
                                 :registrations => "admin/registrations"
                                 #:omniauth_callbacks => "admin/omniauth_callbacks"
                              }

  root 'dashboard/home#index'
  
  namespace :dashboard do
  	resources :home do
        get :show_categories
        get :show_sub_categories
        post :search_articles
        post :subscribe
      end
      resources :comments do
        post :create_reply_comment
        delete :destroy_reply
      end
      resources :profiles, only: [:show] do
         get :show_admin
      end
      resources :galleries do
          get :show_photo
          post :comment
          post :create_reply
          post :create_like
      end
  end

  namespace :admin do
    
    root to: "company_profiles#index"

    resources :articles do
      collection do
        post :article_search
        post :destroy_all
        post :auto_search
        post :auto_search_sidebar
        post :filter
      end
    end

    resources :categories do
      collection do
        post :destroy_all
      end
    end

    resources :advertises do
      collection do
         get :edit_lock
         post :edit_lock_open
       end
    end

    resources :complete_profiles
    resources :profiles
    resources :helps

    resources :galleries do
        collection do
            post :create_reply
        end
    end

    resources :journals do
        collection do
            post :selected_members
            post :selected_checks
            post :filter
            post :get_assign
            get :project_search
            get :add_row_designers
            get :add_row_developers
            get :add_row_checks
            get :new_blank_project
            delete :destroy_add_rows 
        end
    end
    
    resources :journal_issues do
        get :list_data_by_status
        collection do
            get :add_row_watchers
            get :show_task_image
            get :show_task_image
            get :select_project
            get :create_project
            get :edit_status
            delete :destroy_add_rows 
        end
    end

    resources :journal_issue_comment, only: [:create, :show, :destroy]

    resources :company_profiles
    
    resources :contacts, only: [:create, :show, :destroy] do
      post :create_notification_for_all_admins
      post :create_reply_contact
      delete :destroy_reply
    end

    resources :messages do
      collection do
        post :create_reply_contact_for_admin
      end
      delete :destroy_reply
    end

    resources :projects do
      collection do
        post :filter
      end
    end

    resources :calendars do 
      collection do
        get :add_row_watchers
        get :confirmation_invitation
        delete :destroy_member
      end
    end
    #match '/admin/journal_issues', :controller => 'journals', :action => 'index',via: :GET
  end
end

app/models/admin/gallery.rb
require "delayed_job"

class Admin::Gallery < ActiveRecord::Base
	has_many :gallery_comments, :dependent => :destroy
	has_many :gallery_likes, :dependent => :destroy
	accepts_nested_attributes_for :gallery_comments
	
	has_attached_file :photo,
	:style => {
		thumb: "40x40#", large: '50x50>' },
	:url => "/system/:attachment/:id/:style/:basename.:extension",
		:path => ":rails_root/public/system/:attachment/:id/:style/:basename.:extension",
		:default_url => "/assets/:style/missing.jpg"
		validates_attachment_content_type :photo, :content_type => /image/

	def self.admin_gallery_attributes(params)
		params.each do |sub_attribute|
			attribute = self.new
			attribute.title = sub_attribute[1][:title]
			attribute.content = sub_attribute[1][:content]
			attribute.photo = sub_attribute[1][:photo]
			if attribute.save
				unless sub_attribute[1][:photo].blank?
					Cloudinary::Uploader.upload(sub_attribute[1][:photo], :use_filename => true, :public_id => "galleries/#{attribute.id}", :transformation => [{:width => 600, :crop => :limit}])
				end
			end
		end
	end
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::BaseController
	before_action :set_admin_gallery, only: [:show, :edit, :update, :destroy]
	before_filter :setup_page
	# GET /admin/galleries
	# GET /admin/galleries.json
	def index
		@galleries_all = Admin::Gallery.all
		@galleries = Admin::Gallery.order("created_at DESC").paginate(:page => params[:page], :per_page => 16)
		session[:urlBack] = request.original_url
		@page_breadcump = " > Index"
	end

	# GET /admin/galleries/1
	# GET /admin/galleries/1.json
	def show
	end

	# GET /admin/galleries/new
	def new
		@admin_gallery = Admin::Gallery.new
		@page_breadcump = " > form"
	end

	# GET /admin/galleries/1/edit
	def edit
	end

	# POST /admin/galleries
	# POST /admin/galleries.json
	def create
		unless params[:admin_gallery_attributes].blank?
			save_attributes = Admin::Gallery.admin_gallery_attributes(params[:admin_gallery_attributes])
		end
		@admin_gallery = Admin::Gallery.new(admin_gallery_params)

		respond_to do |format|
			if @admin_gallery.save
				unless params[:admin_gallery][:photo].blank?
					preloaded = Cloudinary::Uploader.upload(params[:admin_gallery][:photo], :use_filename => true, :public_id => "galleries/#{@admin_gallery.id}", :transformation => [{:width => 600, :crop => :limit}])
				end
				format.html { redirect_to admin_galleries_path(notice: 'Gallery was successfully created.') }
				format.json { render action: 'show', status: :created, location: @admin_gallery }
			else
				format.html { render action: 'new' }
				format.json { render json: @admin_gallery.errors, status: :unprocessable_entity }
			end
		end
	end

	def create_reply
		@create_reply = Admin::GalleryComment.create(gallery_id: params[:gallery_id], body: params[:content], admin_id: params[:admin_id])
		@create_reply.save
		respond_to do |format|
			format.js
		end
	end

	# PATCH/PUT /admin/galleries/1
	# PATCH/PUT /admin/galleries/1.json
	def update
		respond_to do |format|
			if @admin_gallery.update(admin_gallery_params)
				unless params[:admin_gallery][:photo].blank?
					loaded = Cloudinary::Uploader.destroy("galleries/#{@admin_gallery.id}", :public_id => "galleries/#{@admin_gallery.id}", :invalidate => true)
					preloaded = Cloudinary::Uploader.upload(params[:admin_gallery][:photo], :use_filename => true, :public_id => "galleries/#{@admin_gallery.id}")
				end
				format.html { redirect_to @admin_gallery, notice: 'Gallery was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @admin_gallery.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /admin/galleries/1
	# DELETE /admin/galleries/1.json
	def destroy
		loaded = Cloudinary::Uploader.destroy("galleries/#{@admin_gallery.id}", :public_id => "galleries/#{@admin_gallery.id}", :invalidate => true)
		@admin_gallery.destroy
		respond_to do |format|
			format.html { redirect_to admin_galleries_path(group_id: params[:group_id]) }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_admin_gallery
			@admin_gallery = Admin::Gallery.find(params[:id])
		end

		def setup_page
			@galleries_setup = "selected active"
			@page = "Galleries"
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def admin_gallery_params
			params.require(:admin_gallery).permit(:title, :photo, :content, :gallery_group_id)
		end
end

app/controllers/dashboard/galleries_controller.rb
class Dashboard::GalleriesController < ApplicationController
	before_filter :prepare_session
	skip_before_filter :verify_authenticity_token, :only => [:create_reply, :create_like]

	def index
		session[:url_back_dashboard] = request.original_url
		@galleries = Admin::Gallery.order("created_at DESC").paginate(:page => params[:page], :per_page => 18)
		respond_to do |format|
			format.html
			format.js
		end
	end

	def show
		@gallery_photos = Admin::Gallery.find(params[:id])
	end

	def show_photo
		@gallery_photo = Admin::Gallery.find(params[:gallery_id])
		@comments = Admin::GalleryComment.where("gallery_id = ?", params[:gallery_id])
	end

	def comment
		@dashboard_comment = Admin::GalleryComment.new(gallery_comment_params)
		@dashboard_comment.save
	end

	def prepare_session
		session[:current] = "gallery"
	end

	def create_reply
		@create_reply = Admin::GalleryComment.create(gallery_id: params[:gallery_id], body: params[:content], name: params[:name], email: params[:email])
		@create_reply.save
		respond_to do |format|
			format.js
		end
	end

	def create_like
		@create_like = Admin::GalleryLike.create_like(params)
	end

	private
	def gallery_comment_params
		params.require(:gallery_comment).permit(:gallery_id, :name, :email, :body)
	end
end

app/helpers/admin/galleries_helper.rb
module Admin::GalleriesHelper
end

app/helpers/dashboard/galleries_helper.rb
module Dashboard::GalleriesHelper
end

app/views/admin/galleries/_filter.html.erb
<div class="panel panel-primary">
	<div class="panel-heading filter">
		<%= form_tag filter_admin_projects_path(), remote: true do %>
			<%= hidden_field_tag :filter, "present" %>

		       <%= label_tag :title, "Title : ", class:"floating", style:"margin:7px 5px 0px 0px;" %>
		       <%= text_field_tag :title, "", placeholder:"Title", class:"form-control floating", style:"width:69%; margin-right:10px" %>

		       <%= label_tag :order, "Sort by : ", class:"floating", style:"margin:7px 5px 0px 0px;" %>
		       <%= select_tag :order, options_for_select([['Select',nil],['Top Comment',6],['Top Like',5]]), class:"form-control floating", style:"width:18%; margin-right:10px" %>

		       <span class="clearfix"></span>
		       <br>
		       <%= label_tag :create_start, "Created At : ", class:"floating", style:"margin:7px 5px 0px 0px;" %>
		       <%= text_field_tag :create_start, "", placeholder:"28/04/2015", class:"form-control floating", style:"width:10%; margin-right:10px" %>

		       <%= label_tag :create_end, "To ", class:"floating", style:"margin:7px 5px 0px 0px;" %>
		       <%= text_field_tag :create_end, "", placeholder:"28/04/2015", class:"form-control floating", style:"width:10%; margin-right:10px" %>

			<button class="btn btn-primary ajax">Filter</button>
	       <% end %>
	</div>
</div>

<%#= javascript_include_tag 'filter' %>

app/views/admin/galleries/_form.html.erb
<!-- <div id="modal_profile_edit" class="styled form positions" style="background: none !important;">
			<div class="cl">&nbsp;</div>
			<div id="content">
						 <div class="box">
								
										<div class="box-head">
											<h2>Add Photo</h2>
										</div>
										<%= form_for(@admin_gallery) do |f| %>
													<div class="form">
																 <p>
																			<%= f.label :photo, "Photo", style:"margin-bottom:0px;" %>
																			<span class="foto_prev"></span>
																			<%= f.file_field :photo, class:"field size4 input-file", id: "fileField", :onchange => "readURLGallery(this);"  %>
																 </p>
																 <p>
																			<%= f.label :title %><span>(Required Field)</span>
																			<%= f.text_field :title, class:"field size0" %>
																 </p>
																 <p>
																			 <%= f.label :content %>
																			 <%= f.text_area :content, class:"field size1", style:"height:60px" %>
																 </p>
																 <p>
																				<div class="cl">&nbsp;</div> -->
																				<div class="sub-screen-shoot" dataId="1"><!-- add images place --></div>
																				<!-- <div class="add add_photo_gallery button" type="submit">+| Photo</div>
																 </p>
																 <div class="buttons">
																				<%= link_to "Back", "javascript:void(0)", class:"button-back close-modal-profile" %>
																				<%= f.submit "Save Photo", class:"button" %>
																	</div>
													</div>
										<% end %>
						 </div>
			 </div>
</div> -->
<div class="panel panel-primary">
	<div class="panel-heading">
			<i class="fa fa-edit fa-fw"></i>Gallery Form
	</div>

	<div class="panel-body">
		<div class="row">
			<div class="col-lg-12">
				<%= form_for(@admin_gallery) do |f| %>
					<% if @admin_gallery.errors.any? %>
				            	<%= render partial: "shared/validate_error", locals: { object: @admin_gallery}%>
				      	<% end %>

				      	<table class="table table-bordered table-hover table-striped">
						<thead>
							<tr>
								<th width="30%">Title</th>
								<th width="30%">Photo</th>
								<th width="40%">Description</th>
								<th width="2%">Delete</th>
							</tr>
							<tbody class="sub-category" dataId="<%#= @category_count %>">
								<tr>
									<td><%= f.text_field :title, class:"form-control" %></td>
									<td>
										<span class="foto_prev"></span>
										<%= f.file_field :photo, class:"form-control input-file", id: "fileField", :onchange => "readURLGallery(this);", style:"padding:0px"  %>
									</td>
									<td>
										<%= f.text_area :content, class:"form-control", style:"height:34px" %>
									</td>
									<td>
										<!-- <a href='javascript:void(0)' class='sub'><img src='/assets/min.png' /></a> -->
									</td>
								</tr>
							</tbody>
							<tbody class="sub_screen_shoot">
								
							</tbody>
						</thead>
					</table>
					<%= link_to "<i class='fa fa-plus'></i> Add Photo".html_safe,"javascript:void(0)",class:"btn btn-default add add_photo_gallery", style:"padding: 9px" %>
					<span class="clearfix"></span>
                                	<br>
                                	<div class="modal-footer" style="margin-bottom:-10px">
                                      <button class="btn btn-success floating"><i class="fa  fa-pencil fa-1x"></i>Save</button>
                                      <%= link_to "Back", session[:urlBack], class:"btn btn-default", style:"padding:9px" %>
                                	</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

<%= javascript_include_tag "admin/journal" %>
<%= javascript_include_tag "admin/append_gallery" %>

app/views/admin/galleries/_get_index.html.erb
<div class="panel panel-primary">
      <div class="panel-heading">
          <i class="fa fa-cloud-upload fa-fw"></i><spans class="assign">Photo(s)</spans>
      </div>

      <div class="panel-body">
          <div class="row">
              <div class="col-lg-12">
                  <div class="table-responsive">
                      <center><%= render 'dashboard/shared/ajax_loader' %></center>
                      <%= render "admin/galleries/get_index_data" %>
                      <span class="clearfix"></span>
                      <span class="paggings">
                          <%= render "admin/galleries/shared/paggings" %>
                      </span>
                  </div>

              </div>

          </div>
          <!-- /.row -->
      </div>
      <!-- /.panel-body -->
  </div>

app/views/admin/galleries/_get_index_data.html.erb
<style type="text/css">
	.gallery_admin{width:48% !important; float:left; margin-right:20px}
</style>
<% unless @galleries.present? %>
	<center>No Data Yet</center>
<% else %>
	<% @galleries.each do |gallery| %>
			<table class="gallery_admin table table-bordered table-hover table-striped">
				<tr>
					<td rowspan="3" width="160px"><%= link_to image_tag("http://res.cloudinary.com/sampulkreativ/image/upload/w_150,c_limit/v1/galleries/#{gallery.id}.jpg"), admin_gallery_path(gallery) %></td>
					<tr width="200px">
						<td style="vertical-align: top" height="10px"><b><%= gallery.title %></b></td>
						<td width="60px"><i class="fa fa-comment-o"></i> <b><%= gallery.gallery_comments.count %></b></td>
						<td width="60px"><i class="fa fa-heart-o"></i><b><%= gallery.gallery_likes.count %></b></td>
						<td width="30px">
						<%= link_to '<i class="fa  fa-trash-o fa-1x"></i>'.html_safe, admin_gallery_path(gallery), method: :delete, confirm: "Are you sure?" %>
						</td>
					</tr>
					<tr>
						<td style="vertical-align: top !important" colspan="4"><%= truncate(gallery.content, length: 100) %></td>			
					</tr>
				</tr>				
			</table>
	<% end %>
<% end %>

app/views/admin/galleries/_show_comment_gallery.html.erb
<div id="modal_gallery" class="styled">
	<div id="top_modal"></div>
	<!-- The class for main profile -->
	<div class="scroller scroller_gallery floating" style="float:left">
	    	<div id="content_gallery">
	      <!-- Box -->
	        <!-- Form -->		          
	              <div class="left-photo-gallery">
		             <center>
	                    	<%= cl_image_tag "galleries/#{@admin_gallery.id}",class:"", height:"50%", width:"80%" %>
	                    </center>
	              </div>    
	            <!-- End Form -->
	      <!-- End Box -->
	    	</div>
	</div>
	<!-- The class for comment profile -->
	<%= image_tag "close.gif", class:"close close-modal-gallery close_button" %>
	<div class="scroller_comment">
		<div class="formProfile" style="<%= 'height:550px !important' if @admin_gallery.gallery_comments.count == 0 %>">
			<div class="message_gallery">
				<% unless @admin_gallery.title.blank? %>
					<h3><%= @admin_gallery.title %></h3>
					<label style="font-weight:normal !important"><%= @admin_gallery.content %></label>
					<br><br>
				<%end%>
				<h3>Comment(s)</h3>
				<% unless @admin_gallery %>
					<div class="content_gallery_blank">
						No Comment yet
					</div>
				<% end %>
				<% @admin_gallery.gallery_comments.each do |comment| %>
					<div class="content_gallery">
						<span class="cl">&nbsp;</span>
						<span style="font-size:10px !important">
							<%= comment.created_at.strftime('%d-%b-%Y') %>
							<%= link_to 'Destroy', "javascript:void(0)", method: :delete, data: { confirm: 'Are you sure?' }, :class => "ico del ico-gallery-one" %>
							<%= link_to 'Reply', "javascript:void(0)", class:"ico edit ico-gallery", onclick:"reply(#{comment.id})" %>
						</span>
						<span class="cl">&nbsp;</span>
						<label>Name : </label> <span><%= comment.name %></span>
						<span class="cl">&nbsp;</span>
						<label>E-mail : </label> <span><%= comment.email %></span>
						<span class="cl">&nbsp;</span>
						<label>Comment : </label> <span><%= comment.body %></span>
						<span class="cl">&nbsp;</span>
							<% find_reply_gallery(comment).each do |reply| %>
								<div class="content_gallery_blank" style="400px;">
									<span style="font-size:10px !important">Reply from: <i>Admin</i></span>
									<span class="cl">&nbsp;</span>
									<%= reply.content %>
								</div>
							<% end %>
							<span class="show_comment_gallery_<%= comment.id %>"></span>
							<div style="10px;">
								<span class="content_gallery_blank_<%= comment.id %> undisplay">
									<%= form_tag create_reply_admin_galleries_path(id: comment.id), remote: true do %>
										<%= text_field_tag :content, "",class:"field", style:"width:250px !important" %>
										&nbsp;
										<%= image_submit_tag("edit.gif", width:"6%") %>
									<% end %>
								</span>
								<span class="cl">&nbsp;</span>
							</div>
						<nav></nav>
						<span class="cl">&nbsp;</span>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

<%= javascript_include_tag "scroller" %>
<style type="text/css">
	.undisplay{display: none;}
	.display{display: block;}
</style>

<script>
	$(document).ready(function(){
		$("#modal_gallery").fadeIn();
		$( '.close-modal-gallery' ).click(function( ev ) {  $( '#modal_gallery, #modal_background' ).fadeOut();  ev.preventDefault();} );
		$("#modal_background").click(function(ev){ $( '#modal_gallery, #modal_background' ).fadeOut();  ev.preventDefault(); })
	})
	function reply(id){
		if($('.content_gallery_blank_'+id+'').hasClass("display")){
			$('.content_gallery_blank_'+id+'').removeClass("display")
			$('.content_gallery_blank_'+id+'').addClass("undisplay")
		}else{
			$('.content_gallery_blank_'+id+'').removeClass("undisplay")
			$('.content_gallery_blank_'+id+'').addClass("display")
		}
	}
</script>

app/views/admin/galleries/_show_reply.html.erb
<tr>
	<td><%= image_tag "http://res.cloudinary.com/sampulkreativ/image/upload#{loaded_rand("profile", @create_reply.admin_id)}/profiles/#{@create_reply.admin_id}", class:"admin-comment" %></td>
	<td colspan="2">
		<p><%= @create_reply.body %></p>
		<i class="pull-right" style="font-size:11px"><b><%= @create_reply.name.blank? ? find_profile(@create_reply.admin_id).name : @create_reply.name %></b> on <%= @create_reply.created_at.strftime("%d %M %Y - $H:%m") %></i>
	</td>
</tr>

app/views/admin/galleries/edit.html.erb
<%= render 'form' %>

app/views/admin/galleries/index.html.erb
<%= javascript_include_tag "admin/journal" %>
<%= render "admin/galleries/filter" %>
<%= render "admin/galleries/get_index" %>

app/views/admin/galleries/new.html.erb
<%= render 'form' %>

app/views/admin/galleries/show.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
			<i class="fa fa-cloud-upload fa-fw"></i><spans class="assign"><%= @admin_gallery.title %></spans>
	</div>

	<div class="panel-body">
		<div class="row">
			<div class="col-lg-12">
				<div class="table-responsive">
					<div class="col-lg-6">
						<center><%= image_tag "http://res.cloudinary.com/sampulkreativ/image/upload/w_500,c_limit/v1/galleries/#{@admin_gallery.id}.jpg" %></center>
						<span class="clearfix"></span>
					</div>
					<div class="col-lg-6">
						<b><%= @admin_gallery.title %></b>
						<p><%= @admin_gallery.content %></p>
						<hr>
						<%= link_to "Like".html_safe, dashboard_gallery_create_like_path(gallery_id: @admin_gallery.id, current_ip: request.remote_ip), remote: true, method: :post %>
						<span class="clearfix"></span>
						<table class="gallery_admin table table-bordered table-hover table-striped ">
							<tr>
								<td width="60px">
									<i class="fa fa-comment-o"></i> <b class="comment_count"><%= @admin_gallery.gallery_comments.count %></b>
								</td>
								<td width="60px">
									<i class="fa fa-heart-o"> <b class="like_count"><%= @admin_gallery.gallery_likes.count %></b></i>
								</td>
								<td><span class="pull-right">
								<div class="fb-share-button" data-href="https://jurnalkreativku.herokuapp.com/admin/galleries/<%=@admin_gallery.id%>" data-layout="button_count"></div>
								</span></td>
							</tr>
							<tbody class="comment_place">
								<% @admin_gallery.gallery_comments.each do |comment| %>
									<tr>
										<td>
											<% if comment.admin_id.blank? %>
												<%= image_tag("comment.jpg", class:"admin-comment") %>
											<% else %>
												<%= image_tag "http://res.cloudinary.com/sampulkreativ/image/upload#{loaded_rand("profile", current_admin.id)}/profiles/#{current_admin.id}", class:"admin-comment" %>
											<% end %>
										</td>
										<td colspan="2">
											<p><%= comment.body %></p>
											<i class="pull-right" style="font-size:11px"><b><%= comment.name.blank? ? find_profile(comment.admin_id).name : comment.name %></b> on <%= comment.created_at.strftime("%d/%m/%Y - %H:%m") %></i>
										</td>
									</tr>
								<% end %>
								</tr>
							</tbody>
							<tr>
								<td><%= image_tag "http://res.cloudinary.com/sampulkreativ/image/upload#{loaded_rand("profile", current_admin.id)}/profiles/#{current_admin.id}", class:"admin-comment" %></td>
								<td colspan="2">
									<%= form_tag create_reply_admin_galleries_path, remote: true do %>
										<%= text_area_tag :content, "", placeholder:"Your comment", cols:"48" %>
										<%= hidden_field_tag :admin_id, current_admin.id %>
										<%= hidden_field_tag :gallery_id, @admin_gallery.id %>
										<%= submit_tag "comment", class:"btn btn-default pull-right", style:"padding:2px" %>
									<% end %>
								</td>
							</tr>
						</table>
					</div>
				</div>
				<span class="clearfix"></span>
				<div class="modal-footer" style="margin-bottom:-10px">
                                    <%= link_to '<i class="fa  fa-trash-o fa-1x"></i> Delete'.html_safe, admin_gallery_path(@admin_gallery), method: :delete, class:"btn btn-danger floating", confirm: "Are you sure?" %>
                                    <%= link_to "Back", session[:urlBack], class:"btn btn-default", style:"padding:9px" %>
                              	</div>
			</div>
				<!-- /.row -->
		</div>
	<!-- /.panel-body -->
	</div>
</div>
<%= javascript_include_tag "scroller" %>
<script>
	(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/id_ID/sdk.js#xfbml=1&appId=304923376368561&version=v2.0";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
</script>