config/routes.rb
MyJournal::Application.routes.draw do
  devise_for :admins, :path => "admin",
    :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'forgot_password' },
    :controllers => { :sessions => "admin/sessions",
                                 :registrations => "admin/registrations"
                                 #:omniauth_callbacks => "admin/omniauth_callbacks"
                              }

  root 'dashboard/home#index'
  
  namespace :dashboard do
  	resources :home do
        get :show_categories
        get :show_sub_categories
        post :search_articles
        post :subscribe
      end
      resources :comments do
        post :create_reply_comment
        delete :destroy_reply
      end
      resources :profiles, only: [:show] do
         get :show_admin
      end
      resources :galleries do
          get :show_photo
          post :comment
          post :create_reply
          post :create_like
      end
  end

  namespace :admin do
    
    root to: "company_profiles#index"

    resources :articles do
      collection do
        post :article_search
        post :destroy_all
        post :auto_search
        post :auto_search_sidebar
        post :filter
      end
    end

    resources :categories do
      collection do
        post :destroy_all
      end
    end

    resources :advertises do
      collection do
         get :edit_lock
         post :edit_lock_open
       end
    end

    resources :complete_profiles
    resources :profiles
    resources :helps

    resources :galleries do
        collection do
            post :create_reply
        end
    end

    resources :journals do
        collection do
            post :selected_members
            post :selected_checks
            post :filter
            post :get_assign
            get :project_search
            get :add_row_designers
            get :add_row_developers
            get :add_row_checks
            get :new_blank_project
            delete :destroy_add_rows 
        end
    end
    
    resources :journal_issues do
        get :list_data_by_status
        collection do
            get :add_row_watchers
            get :show_task_image
            get :show_task_image
            get :select_project
            get :create_project
            get :edit_status
            delete :destroy_add_rows 
        end
    end

    resources :journal_issue_comment, only: [:create, :show, :destroy]

    resources :company_profiles
    
    resources :contacts, only: [:create, :show, :destroy] do
      post :create_notification_for_all_admins
      post :create_reply_contact
      delete :destroy_reply
    end

    resources :messages do
      collection do
        post :create_reply_contact_for_admin
      end
      delete :destroy_reply
    end

    resources :projects do
      collection do
        post :filter
      end
    end

    resources :calendars do 
      collection do
        get :add_row_watchers
        get :confirmation_invitation
        delete :destroy_member
      end
    end
    #match '/admin/journal_issues', :controller => 'journals', :action => 'index',via: :GET
  end
end

app/controllers/admin/journals_controller.rb
class Admin::JournalsController < Admin::BaseController
  before_action :set_admin_journal, only: [:show, :edit, :update, :destroy, :destroy_add_rows]
  before_action :set_admin_journal_team, only: [:show, :edit, :update, :destroy_add_rows]
  before_action :set_select_options, only: [:new, :edit, :add_row_designers, :add_row_developers, :add_row_checks, :destroy_add_rows, :new_blank_project, :index, :filter]
  before_action :set_selected, only: [:edit, :update, :show]
  before_action :set_select, only: [:new, :create, :edit, :update, :new_blank_project]
  before_action :set_filter, only: [:index]
  before_filter :setup_page, except: [:new_blank_project, :edit,:show]
  # GET /admin/journals
  # GET /admin/journals.json
  def index
    @admin_journals = Admin::Journal.order("admin_journals.created_at DESC").paginate(:page => params[:page], :per_page => 20).is_allowed(session[:session_admin],nil)
    admin_journals = Admin::Journal.order("admin_journals.created_at DESC").is_allowed(session[:session_admin],nil)
    ids = []
    @admin_journals.each do |journal|
        ids << journal.id
    end
    ids_blank = convert_to_arr_for_query(ids)
    blank = Admin::JournalIssue.find_index_count(ids_blank == ")" ? "(0)" : ids_blank ,current_admin.id,'main')
    @admin_journals_status = blank
    ids_all = []
    admin_journals.each do |journal|
        ids_all << journal.id
    end
    ids_all_blank = convert_to_arr_for_query(ids_all)
    blank_all = Admin::JournalIssue.find_index_count(ids_all_blank == ")" ? "(0)" : ids_all_blank ,current_admin.id,'main')
    @admin_journals_status_all = blank_all
    session[:urlBack] = request.original_url
    @page_breadcump = " > Index"
  end

  # GET /admin/journals/1
  # GET /admin/journals/1.json
  def show
    @admin_journals = []
    @admin_journals << @admin_journal
    params = {"project" => @admin_journal.id}
    find_admin = Admin.find(session[:session_admin])
    ids = []
    @admin_journals.each do |journal|
        ids << journal.id
    end
    convert = convert_to_arr_for_query(ids)
    blanks = Admin::Journal.find_filter(find_admin,convert == ")" ? "(0)" : convert, params)
      @admin_journals_status_filter = blanks


     unless  estimated_time(@admin_journal.start,@admin_journal.end) == 'waiting'
        if estimated_time(@admin_journal.start,@admin_journal.end).to_i == 0
                @estimate = "<b>Now is Deadline</b>"
        elsif estimated_time(@admin_journal.start,@admin_journal.end).to_i < 0
                @estimate = "Out of Deadline"
        else
                time = estimated_time(@admin_journal.start,@admin_journal.end).to_i
                @estimate = "<b>#{time} Day left</b>"
        end
    else
            @estimate = "<b>Waiting</b>"
    end

    @projects = "selected"
    @page = @admin_journal.title
  end

  # GET /admin/journals/new
  def new
    @admin_journal = Admin::Journal.new
    @action = 'new'
    respond_to do |format|
        format.html
        format.js
    end
  end

  def new_blank_project
    @admin_journal = Admin::Journal.new
    @action = 'new'
    @projects = "selected"
    @page = "Project"
    @page_breadcump = " > Creating New"
    respond_to do |format|
        format.html
        format.js
    end
  end

  # GET /admin/journals/1/edit
  def edit
    @action = 'edit'
    @projects = "selected"
    @page = "Project"
    @page_breadcump = " > Editing"
    respond_to do |format|
      format.html
    end
  end

  def project_search
      @admin_journals = Admin::Journal.search_by_params(current_admin.id,params)
      ids = []
       @admin_journals.each do |journal|
              ids << journal.id
       end
       id = convert_to_arr_for_query(ids)
       @admin_journals_status = Admin::JournalIssue.find_index_count(id == ")" ? "(0)" : id,current_admin.id,'search')

        respond_to do |format|
            format.html
        end
  end

  def add_row_designers
    @index = Admin::Journal.generated_number(current_admin.id)
    respond_to do |format|
        format.js
    end
  end

  def add_row_developers
    @index = Admin::Journal.generated_number(current_admin.id)
    respond_to do |format|
        format.js
    end
  end

  def add_row_checks
    @index = Admin::Journal.generated_number(current_admin.id)
    respond_to do |format|
        format.js
    end
  end

def get_assign
    @admins = Admin::JournalIssue.assign(params[:project]).map { |x| ["#{x.name} #{x.last_name}",x.admin_id] }.unshift(['Select',nil])
    render layout: false
  end

  # POST /admin/journals
  # POST /admin/journals.json
  def create
      @admin_journal = Admin::Journal.new(admin_journal_params)
      design = params[:admin_journal][:jornal_team_designers_attributes]
      develop = params[:admin_journal][:journal_team_developers_attributes]
      check = params[:admin_journal][:journal_team_checks_attributes]
      respond_to do |format|
        if @admin_journal.save
          unless design["0"][:admin_id].blank?
            Admin::Journal.save_attributes(@admin_journal.id,design,'design')
          else
            design["0"][:admin_id] = current_admin.id
            Admin::Journal.save_attributes(@admin_journal.id,design,'design')
          end

          unless develop["0"][:admin_id].blank?
            Admin::Journal.save_attributes(@admin_journal.id,develop,'develop')
          else
            develop["0"][:admin_id] = current_admin.id
            Admin::Journal.save_attributes(@admin_journal.id,develop,'develop')
          end

          unless check["0"][:admin_id].blank?
              Admin::Journal.save_attributes(@admin_journal.id,check,'check')
          else
              check["0"][:admin_id] = current_admin.id
              Admin::Journal.save_attributes(@admin_journal.id,check,'check')
          end

          format.html { redirect_to admin_journals_path, notice: 'Project was successfully created.' }
          format.json { render action: 'show', status: :created, location: @admin_journal }
        else
          format.html { render action: 'new' }
          format.json { render json: @admin_journal.errors, status: :unprocessable_entity }
        end
      end
  end

  def filter
    @admin_journals = Admin::Journal.order("admin_journals.created_at DESC").paginate(:page => params[:page], :per_page => 20).is_allowed(session[:session_admin],nil)
    admin_journals = Admin::Journal.order("admin_journals.created_at DESC").is_allowed(session[:session_admin],nil)
    find_admin = Admin.find(session[:session_admin])
    ids = []
    @admin_journals.each do |journal|
        ids << journal.id
    end
    convert = convert_to_arr_for_query(ids)
    blanks = Admin::Journal.find_filter(find_admin,convert == ")" ? "(0)" : convert, params)
      @admin_journals_status_filter = blanks

    ids_all = []
    admin_journals.each do |journal|
        ids_all << journal.id
    end
    convert_all = convert_to_arr_for_query(ids_all)
    blank = Admin::Journal.find_filter(find_admin,convert_all == ")" ? "(0)" : convert, params)
    @admin_journals_status_filter_all = blank
    @assign = params[:assign]
    respond_to do |format|
      format.js
    end
  end

  def selected_members
    member = params[:member].blank? ? 0 : params[:member]
    condition = "admin_id NOT IN (#{member},#{current_admin.id})"
    unless params[:member].blank?
        admin = Admin::Profile.where("{{condition}}".gsub('{{condition}}',condition.to_s))
        @admins_select = admin.map{|x|["#{x.name} #{x.last_name}", x.admin_id]}.unshift(['Select',nil])
    else
        @admins_select = [['Select', nil]]
    end
    render layout: false
  end

  def selected_checks
    member = params[:member].blank? ? 0 : params[:member]
    latest_member = params[:latest_member].blank? ? 0 : params[:latest_member]
    condition = "admin_id NOT IN (#{member}, #{latest_member}, #{current_admin.id})"
    unless params[:member].blank?
            admin = Admin::Profile.where("{{condition}}".gsub('{{condition}}',condition.to_s))
            @admins_select = admin.map { |x| ["#{x.name} #{x.last_name}", x.admin_id] }.unshift(['Select',nil])
    else
            @admins_select = [['Select',nil]]
    end
    render layout: false
  end

  # PATCH/PUT /admin/journals/1
  # PATCH/PUT /admin/journals/1.json
  def update
    respond_to do |format|
      if @admin_journal.update(admin_journal_params)
        Admin::Journal.save_attributes(@admin_journal.id,params[:admin_journal][:jornal_team_designers_attributes],'design')
        Admin::Journal.save_attributes(@admin_journal.id,params[:admin_journal][:journal_team_developers_attributes],'develop')
        Admin::Journal.save_attributes(@admin_journal.id,params[:admin_journal][:journal_team_checks_attributes],'check')
        format.html { redirect_to @admin_journal, notice: 'Journal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/journals/1
  # DELETE /admin/journals/1.json
  def destroy
    Admin::JornalTeamDesigner.delete_all "Journal_id = #{@admin_journal.id}"
    Admin::JournalTeamDeveloper.delete_all "Journal_id = #{@admin_journal.id}"
    Admin::JournalTeamCheck.delete_all "Journal_id = #{@admin_journal.id}"
    @admin_journal.journal_issues.each do |issue|
      issue.journal_issue_images.each do |image|
        loaded = Cloudinary::Uploader.destroy("journal_issue/images/#{image.id}", :public_id => "journal_issue/files/#{image.id}", :invalidate => true)
      end
    end
    @admin_journal.destroy
    respond_to do |format|
      format.html { redirect_to admin_journals_path }
      format.json { head :no_content }
    end
  end

  def destroy_add_rows
    if params[:type] == "designers"
      Admin::JornalTeamDesigner.delete_all "Journal_id = #{params[:id]} AND admin_id = #{params[:admin_id]}"

app/helpers/admin/journals_helper.rb
module Admin::JournalsHelper
	def estimated_time(start_time, end_time)
		if Date.today >= start_time
			time = end_time - Date.today
		else
			time = "waiting"
		end
		return time
	end

	def estimated_time_progress(start_time,end_time)
	end

	def estimated_asignee(journal_id)
		manager = Admin::Journal.where("id = ?", journal_id).count
		designer = Admin::JornalTeamDesigner.where("journal_id = ?", journal_id).count
		developer = Admin::JournalTeamDeveloper.where("journal_id = ?", journal_id).count
		check = Admin::JournalTeamCheck.where("journal_id = ?", journal_id).count
		counts = manager + designer + developer + check
		return counts
	end

	def estimated_asignee_list(journal_id)
		manager = Admin::Journal.find(journal_id)
		designers = Admin::JornalTeamDesigner.where("journal_id = ?", journal_id)
		developers = Admin::JournalTeamDeveloper.where("journal_id = ?", journal_id)
		checks = Admin::JournalTeamCheck.where("journal_id = ?", journal_id)
		asignee = ""
		asignee += "<b>As Project Manager</b>"
		asignee += "</br>"
		asignee += "#{manager.project_manajer}"
		asignee += "</br></br>"
		asignee += "<b>As Project Designer</b>"
		asignee += "</br>"
		designers.each do |designer|
			asignee += "#{find_name(designer.admin_id)}"
			asignee += "</br>"
		end
		asignee += "</br>"
		asignee += "<b>As Project Developer</b>"
		asignee += "</br>"
		developers.each do |developer|
			asignee += "#{find_name(developer.admin_id)}"
			asignee += "</br>"
		end
		asignee += "</br>"
		asignee += "<b>As Project Check</b>"
		asignee += "</br>"
		checks.each do |check|
			asignee += "#{find_name(check.admin_id)}"
			asignee += "</br>"
		end

		return asignee
	end
end

app/views/admin/journals/_form.html.erb
<div class="panel panel-primary">
      <div class="panel-heading">
          <i class="fa fa-edit fa-fw"></i>Project Form
      </div>

      <div class="panel-body">
          <div class="row">
              <div class="col-lg-12">
                  <%= form_for(@admin_journal) do |f| %>
                          <% if @admin_journal.errors.any? %>
                                  <%= render partial: "shared/validate_error", locals: { object: @admin_journal}%>
                          <% end %>
                          <p>
                                <%= f.label :title, "Project Name" %><span style="color:red">*</span>
                                <%= f.text_field :title, class:"form-control" %>
                          </p>

                          <p class="form-group form_costum">
                                <%= f.label :status_id, "Status Task" %>
                                <span class="select_costum_3">
                                       <%= f.select :status_id, options_for_select(@status,@statused) %>
                                </span>
                          </p>

                          <p>
                                <%= f.label :project_manajer, "Project Manajer", class:"form_right" %>
                                <% if @action == 'new' %>
                                      <%= f.text_field :project_manajer, value: find_name(current_admin.id), :disabled=>"disabled", class:"form-control", style:"width:50% !important" %>
                                      <%= f.hidden_field :project_manajer, value: find_name(current_admin.id), class:"field size1 field-dis" %>
                                      <%= f.hidden_field :admin_id, value: current_admin.id, class:"field size1 field-dis" %>
                                <% else %>
                                         <%= f.text_field :project_manajer, :disabled=>"disabled", class:"form-control", style:"width:50% !important" %> 
                                <% end %>
                          </p>
                          
                          <p class="form-group form_costum">
                                <%= f.label :admin_id, "Project Designer", class:"" %>
                                <% if @action == 'new' %>
                                       <span class="select_costum_3">
                                              <%= select_tag :admin_id, options_for_select(@admins), name:"admin_journal[jornal_team_designers_attributes][0][admin_id]", class:"", id:"admin-designer" %>
                                      </span>
                                <% end %>
                                 <%= f.fields_for :jornal_team_designers do |f| %>
                                       <span class="remove-designers">
                                          <span class="select_costum_3">
                                                  <%= f.select :admin_id, options_for_select(@admins, @selected_designer[f.index][:admin_id]), class:"floating" %>
                                          </span>
                                          <% if f.index > 0 %>
                                              <%= link_to image_tag("x-icon.png",class:"right-img"), destroy_add_rows_admin_journals_path({id: @selected_designer[f.index][:journal_id],admin_id: @selected_designer[f.index][:admin_id],type: "designers"}), method: :delete , remote: true, class:"add-designer", onclick:"javascript:$(this).parent().remove()"%>
                                          <% end %>
                                       </span>
                                <% end %>
                                <nav>
                                      <span class="sub-designers" dataId="1"><!-- add designer place --></span>
                                       <%= link_to "Add", add_row_designers_admin_journals_path, remote: true, class:"add btn btn-warning sub-screen fa fa-plus", style:"padding: 9px" %>
                                </nav>
                          </p>

                          <p class="form-group form_costum">
                                 <%= f.label :title, "Project Developer", class:"" %>
                                 <% if @action == 'new' %>
                                       <span class="select_costum_3">
                                              <span class="select_costum_3">
                                                    <%= select_tag :admin_id, options_for_select(@admins), name:"admin_journal[journal_team_developers_attributes][0][admin_id]", class:"",id:"admin-developer" %>
                                              </span>
                                       </span>
                                  <% end %>
                                  <%= f.fields_for :journal_team_developers do |f| %>
                                       <span class="remove-developers">
                                              <span class="select_costum_3">
                                                    <%= f.select :admin_id, options_for_select(@admins, @selected_developer[f.index][:admin_id]), class:"floating" %>
                                              </span>
                                              <% if f.index > 0 %>
                                                <%= link_to image_tag("x-icon.png",class:"right-img"), destroy_add_rows_admin_journals_path({id: @selected_developer[f.index][:journal_id],admin_id: @selected_developer[f.index][:admin_id],type: "developers"}), method: :delete, remote: true, class:"add-designer", onclick:"javascript:$(this).parent().remove()"%>
                                              <% end %> 
                                       </span>
                                    <% end %>
                                  <nav>
                                      <span class="sub-developers" dataId="1"><!-- add developers place --></span>
                                      <%= link_to "Add", add_row_developers_admin_journals_path, remote: true, class:"add btn btn-warning sub-screen fa fa-plus", style:"padding: 9px" %>
                                  </nav>
                          </p>

                          <p class="form-group form_costum">
                                <%= f.label :title, "Project Quality Check", class:"" %>
                                <% if @action == 'new' %>
                                       <span class="select_costum_3">
                                              <%= select_tag :admin_id, options_for_select(@admins), name:"admin_journal[journal_team_checks_attributes][0][admin_id]", class:"",id:"admin-check" %>
                                       </span>
                                <% end %>
                                <%= f.fields_for :journal_team_checks do |f| %>
                                       <span class="remove-checks">
                                              <span class="select_costum_3">
                                                    <%= f.select :admin_id, options_for_select(@admins, @selected_check[f.index][:admin_id]), class:"floating" %>
                                              </span>
                                              <% if f.index > 0 %>
                                                    <%= link_to image_tag("x-icon.png",class:"right-img"), destroy_add_rows_admin_journals_path({id: @selected_check[f.index][:journal_id],admin_id: @selected_check[f.index][:admin_id],type: "checks"}), method: :delete, remote: true, class:"add-designer", onclick:"javascript:$(this).parent().remove()"%>
                                              <% end %> 
                                       </span>
                                <% end %>
                          </p>

                         <div class="form-group form_costum">
                                <%= f.label :start, "Project Estimate Time", class:"" %>
                                <span class="clearfix"></span>
                                <span class="select_costum_4">
                                      <%= f.date_select :start, class:"form-control floating" %>
                                </span>

                                <%= f.label :end, raw("-&nbsp;"), class:"floating" %>
                                <span class="select_costum_4">
                                <%= f.date_select :end, class:"form-control" %>
                                </span>
                          </div>
                          <br><br>
                          <nav class="clearfix"></nav>
                          <%= f.label :description, "Project Description" %>
                          <%= f.text_area :description, class:"form-control ckeditor",rows: 15 %>

                          <br>
                          <p class="modal-footer" style="margin-bottom:-10px">
                                <button class="btn btn-success floating"><i class="fa  fa-pencil fa-1x"></i>Save</button>
                                <%= link_to "Cancel", session[:urlBack], class:"btn btn-default", style:"padding:9px" %>
                          </p>
                  <% end %>
              </div>
          </div>
      </div>
</div>

<script>
    $('.ckeditor').ckeditor({
    toolbar: [
    { name: 'clipboard', items : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ] },
    { name: 'editing', items : [ 'Find','Replace','-','SelectAll','-','Scayt' ] },
    { name: 'insert', items : [ 'Image','Table','HorizontalRule','Smiley','SpecialChar'
             ,'Iframe' ] }, 
    { name: 'basicstyles', items : [ 'Bold','Italic','Strike','-','RemoveFormat','Underline' ] },
    { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote' ] },
    { name: 'links', items : [ 'Link','Unlink','Anchor' ] },
    { name: 'tools', items : [ 'Maximize','-','About' ] },
    { name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },
    ]
  });
</script>

app/views/admin/journals/_get_index.html.erb
<% a =  @admin_journals_status.blank? ? @admin_journals_status_filter.blank? ? 0 : @admin_journals_status_filter.count : @admin_journals_status.count %>
<% if a == 0 %>
        <tr class="body_index"><td colspan="8"><center>No data yet</center></td></tr>
<% end %>
<% @admin_journals.each do |journal| %>
    <% admin_journal = params[:filter].blank? ? journal.journal_issues.order('admin_journal_issues.created_at DESC').data_existed_index(find_admin(session[:session_admin]),'main') : journal.journal_issues.order('admin_journal_issues.created_at DESC').data_existed_index_filter(find_admin(session[:session_admin]),nil,params) %>
    <% admin_journal.each_with_index do |admin_journal_issue,n| %>
            <tr class="<%= generated_priority(admin_journal_issue.priority) %> body_index">
                  <td width="43">
                        <%= link_to "##{admin_journal_issue.no}", admin_journal_issue_path(id: admin_journal_issue.id,id_journal: admin_journal_issue.journal_id), title:"<b>Assign to</b><br>#{find_profile(admin_journal_issue.asignee).name} #{find_profile(admin_journal_issue.asignee).last_name}<br><b>From</b><br>#{find_profile(admin_journal_issue.from).name} #{find_profile(admin_journal_issue.from).last_name}", class:"masterTooltip" %>
                  </td>
                  <td>
                            <%= link_to journal.title, admin_journal_issue_path(id: admin_journal_issue.id,id_journal: admin_journal_issue.journal_id) %>
                  </td>
                  <td width="53"><%= generated_status(admin_journal_issue.status_id).html_safe %></td>
                  <td width="43"><%= find_priority(admin_journal_issue.priority).html_safe %></td>
                  <td>
                      <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%= admin_journal_issue.progress %>%">
                                   <%= admin_journal_issue.progress.blank? ? 0 : admin_journal_issue.progress %>%
                             </div>
                      </div>
                  </td>
                  <td width="353"><%= link_to truncate(strip_tags(admin_journal_issue.title), length: 100), admin_journal_issue_path(id: admin_journal_issue.id,id_journal: admin_journal_issue.journal_id) %></td> 
                  <% if journal.admin_id == session[:session_admin] %>
                      <td width="60px"><%= link_to '<i class="ico fa  fa-pencil"></i> Edit'.html_safe, edit_admin_journal_issue_path(admin_journal_issue, id_journal: admin_journal_issue.journal_id) %></td>
                      <td width="90px"><%= link_to '<i class="ico fa  fa-trash-o"></i> Destroy'.html_safe, admin_journal_issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <% else %>
                      <td colspan="2"><center>Not Allowed</center></td>
                  <% end %>
            </tr>
    <% end %>
<% end %>

app/views/admin/journals/_list_journals.html.erb
<tr>
      <td><%= n + 1 + @admin_journals.offset_value %>.</td>
      <td><%= link_to admin_journal.title, admin_journal_path(admin_journal) %></td>
      <td><%= generated_status(admin_journal.status_id).html_safe %></td>
      <td>
            <%= link_to "#{estimated_asignee(admin_journal.id)} people Assign", admin_journal_path(admin_journal), remote: true, title:"#{raw estimated_asignee_list(admin_journal.id)}", class:"masterTooltip" %>
      </td>
      <td><center><b><%= admin_journal.journal_issues.data_existed_count(current_admin,"home").count %></b></center></td>
      <td> <center><b>
              <% unless  estimated_time(admin_journal.start,admin_journal.end) == 'waiting' %>
                    <% if truncate(estimated_time(admin_journal.start,admin_journal.end).to_s, length: 1).to_i == 0 %>
                          <%= link_to "Now is Deadline", admin_journal_path(admin_journal), remote: true, title:"<b>Start</b><br>#{ admin_journal.start.strftime('%d/%b/%Y')} <br><br> <b>End</b><br> #{admin_journal.end.strftime('%d/%b/%Y')}", class:"masterTooltip" %>
                    <% elsif truncate(estimated_time(admin_journal.start,admin_journal.end).to_s, length: 1).to_i < 0 %>
                          <%= link_to "Out of Deadline", admin_journal_path(admin_journal), remote: true, title:"<b>Start</b><br>#{ admin_journal.start.strftime('%d/%b/%Y')} <br><br> <b>End</b><br> #{admin_journal.end.strftime('%d/%b/%Y')}", class:"masterTooltip" %>
                    <% else %>
                          <%= link_to "#{truncate(estimated_time(admin_journal.start,admin_journal.end).to_s, length: 1).to_i} day left", admin_journal_path(admin_journal), remote: true, title:"<b>Start</b><br>#{ admin_journal.start.strftime('%d/%b/%Y')} <br><br> <b>End</b><br> #{admin_journal.end.strftime('%d/%b/%Y')}", class:"masterTooltip" %>
                    <% end %>
              <% else %>
                    <%= link_to "Waiting", admin_journal_path(admin_journal), remote: true, title:"<b>Start</b><br>#{ admin_journal.start.strftime('%d/%b/%Y')} <br><br> <b>End</b><br> #{admin_journal.end.strftime('%d/%b/%Y')}", class:"masterTooltip" %>
              <% end %>
                </b></center></td>          
      <% if admin_journal.admin_id == current_admin.id %>
            <td  width="5px">
                  <%= link_to 'Edit', edit_admin_journal_path(admin_journal), remote: true, class:"ico edit fa  fa-pencil"%>
            </td>
            <td  width="5px">
                  <%= link_to 'Destroy', admin_journal_path(admin_journal), method: :delete, data: { confirm: 'Are you sure?' }, :class => "ico edit fa  fa-trash-o" %></td>
      <% else %>
              <td  colspan="2"><center>Not Allowed</center></td>
      <% end %>
</tr>

app/views/admin/journals/edit.html.erb
<%= render 'form' %>

app/views/admin/journals/get_assign.html.erb
<%= select_tag :assign, options_for_select(@admins), class:"form-control floating", style:"width:10%; margin-right:10px" %>

app/views/admin/journals/index.html.erb
<%= render "admin/journals/index_main" %>

app/views/admin/journals/new_blank_project.html.erb
<%= render 'form' %>

app/views/admin/journals/project_search.html.erb
<!-- Sidebar -->
<div id="sidebar">
  <%= render :partial => "admin/shared/sidebar" %>
</div>
<!-- Sidebar -->
<%= render partial: 'admin/journals/index', locals: {current_admin: find_profile(current_admin.id), type:"main"} %>