config/routes.rb
MyJournal::Application.routes.draw do
  devise_for :admins, :path => "admin",
    :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'forgot_password' },
    :controllers => { :sessions => "admin/sessions",
                                 :registrations => "admin/registrations"
                                 #:omniauth_callbacks => "admin/omniauth_callbacks"
                              }

  root 'dashboard/home#index'
  
  namespace :dashboard do
  	resources :home do
        get :show_categories
        get :show_sub_categories
        post :search_articles
        post :subscribe
      end
      resources :comments do
        post :create_reply_comment
        delete :destroy_reply
      end
      resources :profiles, only: [:show] do
         get :show_admin
      end
      resources :galleries do
          get :show_photo
          post :comment
          post :create_reply
          post :create_like
      end
  end

  namespace :admin do
    
    root to: "company_profiles#index"

    resources :articles do
      collection do
        post :article_search
        post :destroy_all
        post :auto_search
        post :auto_search_sidebar
        post :filter
      end
    end

    resources :categories do
      collection do
        post :destroy_all
      end
    end

    resources :advertises do
      collection do
         get :edit_lock
         post :edit_lock_open
       end
    end

    resources :complete_profiles
    resources :profiles
    resources :helps

    resources :galleries do
        collection do
            post :create_reply
        end
    end

    resources :journals do
        collection do
            post :selected_members
            post :selected_checks
            post :filter
            post :get_assign
            get :project_search
            get :add_row_designers
            get :add_row_developers
            get :add_row_checks
            get :new_blank_project
            delete :destroy_add_rows 
        end
    end
    
    resources :journal_issues do
        get :list_data_by_status
        collection do
            get :add_row_watchers
            get :show_task_image
            get :show_task_image
            get :select_project
            get :create_project
            get :edit_status
            delete :destroy_add_rows 
        end
    end

    resources :journal_issue_comment, only: [:create, :show, :destroy]

    resources :company_profiles
    
    resources :contacts, only: [:create, :show, :destroy] do
      post :create_notification_for_all_admins
      post :create_reply_contact
      delete :destroy_reply
    end

    resources :messages do
      collection do
        post :create_reply_contact_for_admin
      end
      delete :destroy_reply
    end

    resources :projects do
      collection do
        post :filter
      end
    end

    resources :calendars do 
      collection do
        get :add_row_watchers
        get :confirmation_invitation
        delete :destroy_member
      end
    end
    #match '/admin/journal_issues', :controller => 'journals', :action => 'index',via: :GET
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
   has_attached_file :photo,
    #:style => {
 	#thumb: "100x100#", large: '516x310>' },
 	#:url => "/system/:attachment/:id/:style/:basename.:extension",
    	#:path => ":rails_root/public/system/:attachment/:id/:style/:basename.:extension",
    	:default_url => "/assets/:style/missing.jpg"
  
validates_attachment_content_type :photo, :content_type => /image/

validates :title, :presence => {:message => "can not be blank"}
validates :body, :presence => {:message => "can not be blank"}
validates :category_id, :presence => {:message => "can not be blank"}

has_many :dasboard_comments
belongs_to :category
belongs_to :admin

	def self.search_by_params(params)
		ar = Article.all
		unless params[:title].blank?
			ar = ar.where("LOWER(title) LIKE '%#{params[:title].downcase}%'")
		end

		unless params[:create_start].blank?
			ar = ar.where("DATE(created_at) BETWEEN '#{params[:create_start]}' AND '#{params[:create_end].blank? ? Date.now : params[:create_end]}'")
		end

		unless params[:category].blank?
			ar = ar.where("category_id = #{params[:category]}")
		end

		unless params[:sub_category].blank?
			ar = ar.where("sub_category_id = #{params[:sub_category]}")
		end

		#unless params[:sort_by].blank?
		#	if params[:sort_by] == 2
		#		ar = ar.joins(:comment).where("comment. = #{params[:sort_by]}")
		#	else

		#	end
		#end

		return ar
	end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :prepare_select
  before_filter :setup_page
  skip_before_filter :verify_authenticity_token, :only => [:auto_search]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
    @articles_all = Article.all
    session[:urlBack] = request.original_url
    @page_breadcump = " > Index"
  end
    
  # GET /articles/1
  # GET /articles/1.json
  def show
      if !@article.is_read && @article.admin_id != current_admin.id
        redirect_to admin_articles_url, alert: "You have not permission for access."
      end
    @page_breadcump = " > #{@article.title}"
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    if !@article.is_edit && @article.admin_id != current_admin.id
      redirect_to admin_articles_url, alert: 'You have not permission for access.'
    end
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.admin_id = current_admin.id
    respond_to do |format|
      if @article.save
        unless params[:article][:photo].blank?
          preloaded = Cloudinary::Uploader.upload(params[:article][:photo], :use_filename => true, :public_id => "articles/#{@article.id}")
          rand = RandCloud.generated_rand("articles",@article.id,"/v2#{Random.rand(11)}")
        end
        sub_category = Article.find(@article.id)
        sub_category.update_attributes(sub_category_id: params[:sub_category])

        format.html { redirect_to admin_articles_url, notice: 'Article was successfully created.' }
        #format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def article_search
    articles = Article.search_by_params(params)
    @articles = articles.paginate(:page => params[:page], :per_page => 20)
    @articles_all = articles
    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        unless params[:article][:photo].blank?
          loaded = Cloudinary::Uploader.destroy('article.jpg', :public_id => 'articles/#{@article.id}', :invalidate => true)
          preloaded = Cloudinary::Uploader.upload(params[:article][:photo], :use_filename => true, :public_id => "articles/#{@article.id}")
          rand = RandCloud.generated_rand("articles",@article.id,"/v2#{Random.rand(11)}")
        end
        @article.update_attributes(sub_category_id: params[:sub_category])

        format.html { redirect_to admin_articles_url, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    if !@article.is_delete && @article.admin_id != current_admin.id
      redirect_to admin_articles_url, alert: 'You have not permission for access.'
    else
      comment = Dashboard::Comment.delete_all "article_id = #{@article.id}"
      loaded = Cloudinary::Uploader.destroy("articles/#{@article.id}", :public_id => "articles/#{@article.id}", :invalidate => true)
      @article.destroy
      respond_to do |format|
        format.html { redirect_to admin_articles_url }
        format.json { head :no_content }
      end
    end
  end

  def destroy_all
    unless params[:selected].blank?
      id_params = params[:selected]      
      id = convert_to_arr_for_query(id_params)
      Article.delete_all "id in #{id}"
      Dashboard::Comment.delete_all "article_id in #{id}"
      
      respond_to do |format|
        format.html { redirect_to admin_articles_url }
        format.json { head :no_content }
      end
     end
  end

  def auto_search
    unless params[:category].blank?
      sub_category = Admin::SubCategory.where("category_id = ?", params[:category])
      @sub_category_select = sub_category.map{|x|[x.name, x.id]}.unshift(['Select',nil])
      unless params[:id].blank?
        @sub_category_selected = Article.find(params[:id]).sub_category_id
      end
    else
      @sub_category_select = [['Select', nil]]
    end
    render layout: false
  end

  def auto_search_sidebar
    unless params[:category].blank?
      sub_category = Admin::SubCategory.where("category_id = ?", params[:category])
      @sub_category_sidebar_select = sub_category.map{|x|[x.name, x.id]}.unshift(['Sub Category',nil])
    else
      @sub_category_sidebar_select = [['Sub Category', nil]]
    end
    render layout: false
  end
  
  def prepare_select
    @category = Admin::Category.all.map{|x| [x.name, x.id]}.unshift(['Select',nil])
    @sub_category_select = [['Select', nil]]
    @sort = [['Select', nil],['Top View', 1], ['Top Comment', 2]]
    @profile = [["Annonymous","1.gif"], ["General","2.gif"],["Private","3.gif"],["Geust","4.gif"]].unshift(['-- Select Profile --', nil])
  end

  def setup_page
      @articles_page = "selected active"
      @page = "Articles"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])     
      @selected = @article.category_id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :photo, :category_id, :is_read, :is_edit, :is_delete, :admin_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def find_article_comment(id)
		Dashboard::Comment.find_all_by_article_id(id)
	end

	def find_category(id)
		unless id.blank? || id == 0
			category = Admin::Category.find_by_id(id)
			unless category == nil
				category.name
			else
				category = 'ect'
			end
		else
			category = 'ect'
		end
	end

	def find_sub_category(id)
		unless id.blank? || id == 0
			sub_category = Admin::SubCategory.find_by_id(id)
			unless sub_category == nil
				sub_category.name
			else
				sub_category = 'ect'
			end
		else
			sub_category = 'ect'
		end		
	end
end

app/views/admin/articles/shared/_form_comment.html.erb
<%= form_for(:dashboard_comment, url: dashboard_comments_path, remote: true) do |f| %>
	<div class="field">
		<%= f.hidden_field :article_id, value: @article.id %>
	</div>
	<p>
		<%= f.text_field :name, class:"form-control size-1", placeholder:"Name" %>
		<div id="error_name" class="error"></div>
	</p>
	<p>
		<%= f.text_field :email, class:"form-control size-1", placeholder:"Email" %>
	</p>
	<p class="form-group form_costum">
		<span class="select_costum_3">
			<%= f.select :profile, options_for_select(@profile) %>
		</span>
	</p>
	<div class="field">
		<%= f.text_area :body, class:"form-control", rows: "5", style:"width:50%",id:"textarea-label" %>
	<div id="error_body" class="error"></div>

	<br>
	<div class="post_content">
		<%= link_to "Post Comment", "javascript:void(0)", id:"submit-form", dataId:"contact_for_comment", class:"btn btn-info" %>
	</div>
<% end %>

app/views/admin/articles/shared/_form_reply_comment.html.erb
<%= form_tag dashboard_comment_create_reply_comment_path(comment_id: params[:id]), class:"sub_comment_for_remove_#{params[:id]}", remote: true do %>
	<div class="sub_comment_box">
		<a href='javascript:void(0)' onclick='javascript:$(this).parent().remove();$(".reply_button_<%= params[:id] %>").show();' class="pull-right">X</a>

	    	<div class="field">
			<%= hidden_field_tag :comment_id,"", value: params[:id] %>
			<%= hidden_field_tag :admin_id,"", value: current_admin.id %>
		</div>
		<p>
			<%= text_field_tag :name,"", value: current_admin.profile.name, class:"form-control size-2", placeholder:"Name", readonly: true %>
			<div id="error_name" class="error"></div>
		</p>
		<p>
			<%= text_field_tag :email,"", value: current_admin.email ,class:"form-control size-2", placeholder:"Email", readonly: true %>
		</p>
		<p class="form-group form_costum">
			<span class="select_costum_3">
				<%= hidden_field_tag :profile, "", value:"2.gif" %>
			</span>
		</p>
		<div class="field">
			<%= text_area_tag :body,"", class:"form-control", rows: "5",id:"textarea-label" %>
		<div id="error_body" class="error"></div>

		<br>
		<div class="post_content">
			<%= submit_tag "Post Comment", class:"btn btn-info" %>
		</div>
    	</div>
<% end %>

app/views/admin/articles/shared/_new_show_comment.html.erb
<div class="comment_box">
	<%=  image_tag  dashboard_comment.profile %>
	<nav>
		<%= link_to "#{dashboard_comment.name}", dashboard_comment_path(dashboard_comment), remote: true %>
		<i><%= dashboard_comment.email %></i>
	</nav>
	<span>on : <%= dashboard_comment.created_at.strftime("%d - %B - %Y") %> said:</span>
	<nav class="clearfix"></nav>
	<span class="justify"><%= dashboard_comment.body %></span>
	<nav class="clearfix"></nav>
	<nav class="pull-right">
		<%= link_to '<span class="fa fa-pencil"></span>Reply'.html_safe, dashboard_comment_path(dashboard_comment,reply: "true"), remote: true %> |
		<%= link_to '<span class="fa fa-trash-o"></span>Destroy'.html_safe, dashboard_comment_path(article_id: params[:dashboard_comment][:article_id], id:dashboard_comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
	</nav>
	<nav class="clearfix"></nav>
	<div id="reply-comment-place-<%= dashboard_comment.id %>"></div>
	<div id="new-reply-comment-place-<%= dashboard_comment.id %>"></div>
</div>
<br>

app/views/admin/articles/shared/_pagination.html.erb
<div class="left">Show: <b class="shows"><%= @articles.blank? ? 0 : @articles.per_page > @articles.count ? @articles.count : @articles.per_page %></b> data From: <b class="froms"><%= @articles_all.blank? ? 0 : @articles_all.count %></b> data
	<span class="pull-right">
		<span class="paginate">
			<%= will_paginate @articles %>&nbsp;
		</span>
		<%= link_to '<span class="fa  fa-pencil-square fa-1x"></span>New Article'.html_safe, new_admin_article_path, class:"btn btn-primary" %> 
	</span>
</div>

app/views/admin/articles/shared/_reply_comment.html.erb
<div class="sub_comment_box hidden_<%="#{@reply_comment.id}"%>">
	<%=  image_tag  "1.gif" %>
	<nav><%= link_to "#{@reply_comment.admin.profile.name}", "#" %> <i><%= @reply_comment.admin.email%></i></nav>
	<span>on : <%= @reply_comment.created_at.strftime("%d - %B - %Y") %> said:</span>
	<nav class="clearfix"></nav>
	<%= @reply_comment.body %>
	<nav class="clearfix"></nav>
	<%= link_to '<span class="fa fa-trash-o"></span>Destroy'.html_safe, dashboard_comment_destroy_reply_path(@reply_comment), method: :delete, remote: true, onclick:"javascript:$(this).parent().remove();",class:"pull-right" %>
	<nav class="clearfix"></nav>
</div>

app/views/admin/articles/shared/_reply_comments.html.erb
<% reply_comments.each do |comment| %>
	<div class="sub_comment_box hidden_<%="#{comment.id}"%>">
  		<%=  image_tag  "1.gif" %>
    		<nav><%= link_to "#{comment.admin.profile.name}", "#" %> <i><%= comment.admin.email%></i></nav>
    		<span>on : <%= comment.created_at.strftime("%d - %B - %Y") %> said:</span>
    		<nav class="clearfix"></nav>
    		<%= comment.body %>
    		<nav class="clearfix"></nav>
    		<%= link_to '<span class="fa fa-trash-o"></span>Destroy'.html_safe, dashboard_comment_destroy_reply_path(comment), method: :delete, remote: true, onclick:"javascript:$(this).parent().remove();", class:"pull-right" %>
    		<nav class="clearfix"></nav>
    	</div>
<% end %>