config/routes.rb
MyJournal::Application.routes.draw do
  devise_for :admins, :path => "admin",
    :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'forgot_password' },
    :controllers => { :sessions => "admin/sessions",
                                 :registrations => "admin/registrations"
                                 #:omniauth_callbacks => "admin/omniauth_callbacks"
                              }

  root 'dashboard/home#index'
  
  namespace :dashboard do
  	resources :home do
        get :show_categories
        get :show_sub_categories
        post :search_articles
        post :subscribe
      end
      resources :comments do
        post :create_reply_comment
        delete :destroy_reply
      end
      resources :profiles, only: [:show] do
         get :show_admin
      end
      resources :galleries do
          get :show_photo
          post :comment
          post :create_reply
          post :create_like
      end
  end

  namespace :admin do
    
    root to: "company_profiles#index"

    resources :articles do
      collection do
        post :article_search
        post :destroy_all
        post :auto_search
        post :auto_search_sidebar
        post :filter
      end
    end

    resources :categories do
      collection do
        post :destroy_all
      end
    end

    resources :advertises do
      collection do
         get :edit_lock
         post :edit_lock_open
       end
    end

    resources :complete_profiles
    resources :profiles
    resources :helps

    resources :galleries do
        collection do
            post :create_reply
        end
    end

    resources :journals do
        collection do
            post :selected_members
            post :selected_checks
            post :filter
            post :get_assign
            get :project_search
            get :add_row_designers
            get :add_row_developers
            get :add_row_checks
            get :new_blank_project
            delete :destroy_add_rows 
        end
    end
    
    resources :journal_issues do
        get :list_data_by_status
        collection do
            get :add_row_watchers
            get :show_task_image
            get :show_task_image
            get :select_project
            get :create_project
            get :edit_status
            delete :destroy_add_rows 
        end
    end

    resources :journal_issue_comment, only: [:create, :show, :destroy]

    resources :company_profiles
    
    resources :contacts, only: [:create, :show, :destroy] do
      post :create_notification_for_all_admins
      post :create_reply_contact
      delete :destroy_reply
    end

    resources :messages do
      collection do
        post :create_reply_contact_for_admin
      end
      delete :destroy_reply
    end

    resources :projects do
      collection do
        post :filter
      end
    end

    resources :calendars do 
      collection do
        get :add_row_watchers
        get :confirmation_invitation
        delete :destroy_member
      end
    end
    #match '/admin/journal_issues', :controller => 'journals', :action => 'index',via: :GET
  end
end

app/models/dashboard.rb
module Dashboard
  def self.table_name_prefix
    'dashboard_'
  end
end

app/models/dashboard/comment.rb
class Dashboard::Comment < ActiveRecord::Base
	belongs_to :article

	has_many :reply_comments
end

app/models/dashboard/reply_comment.rb
class Dashboard::ReplyComment < ActiveRecord::Base
	belongs_to :comment
	belongs_to :admin
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
	def index;end
end

app/controllers/dashboard/comments_controller.rb
class Dashboard::CommentsController < ApplicationController
  before_action :set_dashboard_comment, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => [:create]
  # GET /dashboard/comments
  # GET /dashboard/comments.json
  def index
    @dashboard_comments = Dashboard::Comment.all
  end

  # GET /dashboard/comments/1
  # GET /dashboard/comments/1.json
  def show
    respond_to do |format|
      	format.js {@dashboard_comment}
    end
  end

  # GET /dashboard/comments/new
  def new
    @dashboard_comment = Dashboard::Comment.new
  end

  # GET /dashboard/comments/1/edit
  def edit
  end

  # POST /dashboard/comments
  # POST /dashboard/comments.json
  def create
    @dashboard_comment = Dashboard::Comment.new(dashboard_comment_params)

    respond_to do |format|
      if @dashboard_comment.save
        AdminMailer.delay(:queue => 'notification_to_admin_for_article_comment', :priority => 2).notification_to_admin_for_article_comment(@dashboard_comment.id)

        flash[:nostice] = 'Comment was successfully created.'
        format.html { redirect_to @dashboard_comment }
        format.json { render action: 'show', status: :created, location: @dashboard_comment }
        format.js {@dashboard_comment = Dashboard::Comment.where('article_id = ?',params[:dashboard_comment][:article_id]).last}
      else
        format.html { render action: 'new' }
        format.json { render json: @dashboard_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_reply_comment
    reply_comment = Dashboard::ReplyComment.create(body: params[:body], comment_id: params[:comment_id], admin_id: params[:admin_id])
    reply_comment.save

    respond_to do |format|
      format.js { @reply_comment =  Dashboard::ReplyComment.where("comment_id = ?", reply_comment.comment_id).last }
    end
  end

  # PATCH/PUT /dashboard/comments/1
  # PATCH/PUT /dashboard/comments/1.json
  def update
    respond_to do |format|
      if @dashboard_comment.update(dashboard_comment_params)
        format.html { redirect_to @dashboard_comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dashboard_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/comments/1
  # DELETE /dashboard/comments/1.json
  def destroy
    @dashboard_comment.destroy
    reply_comment = Dashboard::ReplyComment.find_by_comment_id(params[:id])
    unless reply_comment.blank?
      reply_comment.destroy
    end

    respond_to do |format|
      unless params[:article_id].blank?
        format.html { redirect_to admin_article_path(params[:article_id]) }
      else
        format.html { redirect_to dashboard_comments_url }
      end
      format.json { head :no_content }
      format.js
      flash[:notice] = 'Comment was successfully deleted.'
    end
  end

  def destroy_reply
    reply_comment = Dashboard::ReplyComment.find(params[:comment_id])
    reply_comment.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard_comment
      @dashboard_comment = Dashboard::Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_comment_params
      params.require(:dashboard_comment).permit(:article_id, :name, :email, :body, :profile)
    end
end

app/controllers/dashboard/galleries_controller.rb
class Dashboard::GalleriesController < ApplicationController
	before_filter :prepare_session
	skip_before_filter :verify_authenticity_token, :only => [:create_reply, :create_like]

	def index
		session[:url_back_dashboard] = request.original_url
		@galleries = Admin::Gallery.order("created_at DESC").paginate(:page => params[:page], :per_page => 18)
		respond_to do |format|
			format.html
			format.js
		end
	end

	def show
		@gallery_photos = Admin::Gallery.find(params[:id])
	end

	def show_photo
		@gallery_photo = Admin::Gallery.find(params[:gallery_id])
		@comments = Admin::GalleryComment.where("gallery_id = ?", params[:gallery_id])
	end

	def comment
		@dashboard_comment = Admin::GalleryComment.new(gallery_comment_params)
		@dashboard_comment.save
	end

	def prepare_session
		session[:current] = "gallery"
	end

	def create_reply
		@create_reply = Admin::GalleryComment.create(gallery_id: params[:gallery_id], body: params[:content], name: params[:name], email: params[:email])
		@create_reply.save
		respond_to do |format|
			format.js
		end
	end

	def create_like
		@create_like = Admin::GalleryLike.create_like(params)
	end

	private
	def gallery_comment_params
		params.require(:gallery_comment).permit(:gallery_id, :name, :email, :body)
	end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController
	before_filter :prepare_select, :prepare_article_default, :prepare_session
      skip_before_filter :verify_authenticity_token, :only => [:search_articles, :subscribe]
  def index
      @articles = @articles_default
      session[:url_back_dashboard] = request.original_url
      session[:ip] = request.remote_ip
      respond_to do |format|
        format.html
      end
  end

  def show
       @status = "Article"
  	@article = Article.find(params[:id])
  	@article_comments = Dashboard::Comment.where("article_id = ? ", params[:id]).order("id DESC")
       @similiar_articles = Article.where("(category_id = ? OR sub_category_id = ?) AND id NOT IN (?)", @article.category_id, @article.sub_category_id, params[:id]).limit(4).order("id DESC");
       if request.remote_ip != session[:ip]
          result = @article.count_view.blank? ? 0 : @article.count_view
          result = result + 1
          @article.update_attributes(count_view: result)
       end
  end

  def search_articles
    @articles = Article.where("LOWER(title) like '%#{params[:title]}%'").order("created_at DESC").paginate(:page => params[:page], :per_page => 5  )
  end

  def prepare_select
    @profile = [["Annonymous","1.gif"], ["General","2.gif"],["Private","3.gif"],["Geust","4.gif"]].unshift(["Select",nil])
  end

  def show_categories
    unless params[:home_id].blank?
      @articles = Article.where("category_id = ?", params[:home_id]).order("created_at DESC").paginate(:page => params[:page], :per_page => 5  )
    else
      @articles = @articles_default
    end

    session[:url_back_dashboard] = request.original_url

    respond_to do |format|
      format.html
    end
  end

  def show_sub_categories
    unless params[:home_id].blank?
      @articles = Article.where("sub_category_id = ? ", params[:home_id]).order("created_at DESC").paginate(:page => params[:page], :per_page => 5  )  
    else
      @articles = @articles_default
    end

    session[:url_back_dashboard] = request.original_url
    
    respond_to do |format|
      format.html
    end
  end

  def subscribe
    if params[:email].present?
      @error = false
    else
      @error = true
    end
  end

  def prepare_article_default
    @articles_default = Article.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
  end

  def prepare_session
      session[:current] = nil
  end
end

app/controllers/dashboard/profiles_controller.rb
class Dashboard::ProfilesController < ApplicationController
	before_filter :prepare_select, :prepare_session
	before_action :admin, only: [:show_admin]
	
	def show
		@company_profile = Admin::CompanyProfile.last
		@company_comments = Admin::ContactCompany.where("admin_id = ? ", @company_profile.id)
		@article = @company_profile
		@admins = Admin::Profile.all
	end

	def show_admin
		@admin_comments = Admin::Contact.find_all_by_admin_id(params[:profile_id])
		
		respond_to do |format|
			format.js

			format.html {render :partial => "dashboard/profiles/show_admin_profile"}
		end
	end

	def prepare_select
	    	@profile = [["Annonymous","1.gif"], ["General","2.gif"],["Private","3.gif"],["Geust","4.gif"]].unshift(["Select",nil])
	end

	def prepare_session
		session[:current] = "about"
	end

	private
	def admin
		@admin_profile = Admin::Profile.find(params[:profile_id])
	end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/dashboard/calendar_helper.rb
module Dashboard::CalendarHelper
	def calendar(date = Date.today, &block)
		Calendar.new(self, date, block).table
	end
end

app/helpers/dashboard/comments_helper.rb
module Dashboard::CommentsHelper
end

app/helpers/dashboard/galleries_helper.rb
module Dashboard::GalleriesHelper
end

app/helpers/dashboard/home_helper.rb
module Dashboard::HomeHelper
	def counting_comment(article_id)
		Dashboard::Comment.where("article_id = ?", article_id).count
	end
end

app/helpers/dashboard/profiles_helper.rb
module Dashboard::ProfilesHelper
end

app/views/dashboard/shared/_ajax_loader.html.erb
<div id="ajax_loader" style="display:none">
	<center><%= image_tag "ajax-loader.gif", class:"loader" %></center>
</div>

app/views/dashboard/shared/_ajax_loader_big.html.erb
<div id="ajax_loader_big">
	<center><%= image_tag "load-big.gif", width:"20%" %></center>
</div>

app/views/dashboard/shared/_end_footer.html.erb
<div class="end">
	<div class="container clearfix">
		<div class="row">
			<div class="col-xs-12 col-sm-3">
				<section class="down2x">
					<article>
						&copy; Copyright <span>Sampulkreativ</span> 2015
					</article>
				</section>
			</div>
		</div>
	</div>
</div>

app/views/dashboard/shared/_footer.html.erb
<div class="col-xs-12 col-sm-3">
	<section class="down2x">
		<article>
			<b>Recent Posts</b>
			<% @recent_posts.each do |article| %>
                    	<nav class="clearfix down2x"></nav>
                              	<%= image_tag "share.jpg", title:"Pin", class:"col-sm-2",style:"padding-left:0px" %>
                              	<content>
						<%= link_to truncate(strip_tags(article.title), :length => 50), dashboard_home_path(article), style:"margin-top:-10px" %>
						<nav><%= article.created_at.strftime("%d - %B - %Y") %></nav>
					</content>
					<hr>
              	<% end %>
		</article>
	</section>
</div>
<div class="col-xs-12 col-sm-3">
	<section class="down2x">
		<article>
			<b>Tags</b>
			<nav class="clearfix down2x"></nav>
			<a href="javascript:void(0)"><nav class="category"><span>GALLERY</span></nav></a>
			<a href="javascript:void(0)"><nav class="category"><span>LINKS</span></nav></a>
			<a href="javascript:void(0)"><nav class="category"><span>QOUTE</span></nav></a>
			<a href="javascript:void(0)"><nav class="category"><span>VIDEOS</span></nav></a>
		</article>
	</section>
</div>
<div class="col-xs-12 col-sm-3">
	<section class="down2x">
		<article>
			<b>Subscribe</b>
			<%= form_tag dashboard_home_subscribe_path(home_id: 0), remote: true do %>
				<nav class="clearfix down2x"></nav>
				<input type="text" placeholder="Your Email Address" class="subscribe" name="email">
				<nav class="clearfix down1x"></nav>
				<button class="btn btn-warning" id="subscribe_btn">Subscribe Now</button>
			<% end %>
		</article>
	</section>
</div>
<div class="col-xs-12 col-sm-3">
	<section class="down2x">
		<article>
			<b>Categories</b>
			<nav class="clearfix down2x"></nav>
			<ul>
				<% @categories_list.each do |category| %>
					<li>
						<%= link_to category.name, dashboard_home_show_categories_path(category) %>
						<hr>
					</li>
				<% end %>
			</ul>
		</article>
	</section>
</div>

app/views/dashboard/shared/_header_content.html.erb
<div class="navbar navbar-fixed-top navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="/" class="navbar-brand">SampulKreativ</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li>
					<a href="/" class="<%= params[:controller] == 'dashboard/home' ? 'active' : '' %>">
						<b><span class="glyphicon glyphicon-home"></span> Home</b>
					</a>
				</li>
				<li>
					<a href="/dashboard/galleries" class="<%= params[:controller] == 'dashboard/galleries' ? 'active' : '' %>">
						<b><span class="glyphicon glyphicon-stats"></span> Gallery</b>
					</a>
				</li>
				<li>
					<a href="/admin/login"><b><span class="glyphicon glyphicon-log-in"></span> Sign In</b></a> 
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/dashboard/shared/_loading.html.erb
<div class="modal fade over-flow-block table-responsive" id="waitDialog">
  <div class="modal-dialog">
    <div class="modal-content" style="margin: 35% auto 65% auto;">
      <div class="modal-header">
		    <h4 class="modal-title">Processing...</h4>
      </div>
		  <div class="modal-body">
			  <div class="progress progress-striped active" id="progress-parent">
		      <div class="progress-bar progress-bar-warning" id="wait-progress"></div>
		    </div>
		  </div>
    </div>
  </div>
</div>

app/views/dashboard/shared/_modal.html.erb
<div class="modal fade over-flow-none table-responsive" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Modal Title</h4>
			</div>
			<div class="modal-body opa">
				<%= render 'dashboard/shared/ajax_loader_big' %>
			</div>
			<div class="modal-footer">
				<div class="modal-footnote pull-left"></div>
				<button type="button" class="btn btn-primary modal-save"><i class='fa fa-save'></i> Save</button>
				<button type="button" class="btn btn-default modal-close" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

app/views/dashboard/shared/_notice.html.erb
<div  id="notice">
	<div class="msg-notice msg-ok"><%= flash[:warning] %><a href="javascript:void(0)" class="close-notice close"></a><br></div><br>
</div>
<script>
	$(".close-notice").click(function(){
		$("#notice").remove()
	})
</script>

app/views/dashboard/shared/_pre_footer.html.erb
<div id="top-panel">
          <div id="top-panel-top">
            <div id="top-panel-bottom">
              <div class="top-panel-box">
                <h3>Featured Posts</h3>
                <ul>
                <% @recent_posts.each do |article| %>
                      <li>
                              <span>22-09-2008</span>
                              <%= link_to truncate(strip_tags(article.title), :length => 50), dashboard_home_path(article), style:"margin-top:-10px" %>
                      </li>
                <% end %>
                </ul>
              </div>
              <div class="top-panel-about">
                <h3>About Our blog</h3>
                <div class="textwidget">
                      <%= image_tag "http://res.cloudinary.com/sampulkreativ/image/upload#{loaded_rand("company", Admin::CompanyProfile.last.id)}/company/#{Admin::CompanyProfile.last.id}",width:"130", height:"115" %>
                      <%= raw Admin::CompanyProfile.last.vission %>
                </div>
              </div>
              <div class="top-panel-box">
                <h3>Recent Comments</h3>
                <ul>
                  <% @recent_comments.each do |comment| %>
                      <li>
                              <span><%= comment.name %>:</span>
                              <%= link_to truncate(strip_tags(comment.body), :length => 50), dashboard_home_path(comment.article_id), style:"margin-top:-10px" %>
                      </li>
                <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>

app/views/dashboard/shared/_sidebar.html.erb
<style type="text/css">
	.container p a:hover{
		background-color: #fff !important;
	}
</style>
<!-- MAIN RIGHT SIDEBAR -->
	<div class="col-sm-4 side pull-right sidebar down2x">
		<section class="sidebarside">
			<%= form_tag dashboard_home_search_articles_path(home_id: 0), remote: true, id: "search_dashboard" do %>
				<article><%= text_field_tag :title, "", placeholder:"Search Article Here" %></article>
			<% end %>
		</section>
		<br>
		<nav class="clearfix"></nav>
		<section class="sidebarside tabs">
			<article class="tabs_article active" id="tab1_acticle">
				<ul class="tab-links">
					<li>
						<a href="#tab1">Popular Post</a>
					</li>
				</ul>
			</article>
			<article class="tabs_article" id="tab2_acticle">
				<ul class="tab-links">
					<li>
						<a href="#tab2">Recent Post</a>
					</li>
				</ul>
			</article>
			<div class="tab-content">
				<div id="tab1" class="tab active">
					<article>
					<br><br><br>
					<% @popular_posts.each do |article| %>
						<%= link_to image_tag("http://res.cloudinary.com/sampulkreativ/image/upload#{loaded_rand("articles", article.id)}/articles/#{article.id}", width:"300%"), dashboard_home_path(article), class:"col-sm-2",style:"padding-left:0px" %>
						<p style="margin-left:110px">
							<b><%= link_to article.title, dashboard_home_path(article) %></b>
							<nav style="padding-left:120px"><%= "#{article.created_at.strftime('%d - %B - %Y')} " %></nav>
						</p>
						<br>
					<% end %>
					</article>
				</div>
				<div id="tab2" class="tab">
					<article>
					<br><br><br>
					<% @recent_posts.each do |article| %>
						<%= link_to image_tag("http://res.cloudinary.com/sampulkreativ/image/upload#{loaded_rand("articles", article.id)}/articles/#{article.id}", width:"300%"), dashboard_home_path(article), class:"col-sm-2",style:"padding-left:0px" %>
						<p style="padding-left:120px">
							<b><%= link_to article.title, dashboard_home_path(article) %></b>
							<nav style="padding-left:120px"><%= "#{article.created_at.strftime('%d - %B - %Y')} " %></nav>
						</p>
						<br>
					<% end %>
					</article>
				</div>
			</div>
		</section>
		<br>
		<nav class="clearfix"></nav>
		<section class="sidebarside down2x">
			<article>
				<nav><b>Social Media</b></nav>
				<a href="javascript:void(0)">
					<nav class="socmed_1 down1x"></nav><div class="link down1x">Sampulkreativ Facebook Fans Page</div>
				</a>
				<nav class="clearfix"></nav>
				<a href="javascript:void(0)">
					<nav class="socmed_2"></nav><div class="link">Sampulkreativ Twitter Fans Page</div>
				</a>
				<nav class="clearfix"></nav>
				<a href="javascript:void(0)">
					<nav class="socmed_3"></nav><div class="link">Sampulkreativ Google+ Fans Page</div>
				</a>
				<nav class="clearfix"></nav>
			</article>
		</section>
		<nav class="clearfix"></nav>
		<section class="sidebarside down2x">
			<article>
				<nav><b>Category</b></nav>
				<div class="panel-group down1x" id="accordion" role="tablist" aria-multiselectable="true">
					<div class="panel panel-default">
						<% @categories_list.each do |category| %>
							<div class="panel-heading" role="tab" id="heading<%= category.id %>">
							  	<h4 class="panel-title">
							    		<a data-toggle="collapse" data-parent="#accordion" href=".collapse<%= category.id %>" aria-expanded="true" aria-controls="collapse<%= category.id %>" class="collap">
							      			<%= category.name %>
							    		</a>
							  	</h4>
							</div>
							<div id="" class="panel-collapse collapse collapse<%= category.id %>" role="tabpanel" aria-labelledby="heading<%= category.id %>">
								<% category.sub_categories.each do |sub_category| %>
									<div class="panel-body list-group">
									 	<%= link_to sub_category.name, dashboard_home_show_sub_categories_path(sub_category) %>
									</div>
								<% end %>
							</div>
						<% end %>
					</div>
				</div>
				<nav class="clearfix"></nav>
			</article>
		</section>
		<br>
		<nav class="clearfix"></nav>
		<section class="sidebarside">
			<article>
				<nav><b>Sampulkreativ Journal</b></nav>
				<table class="down1x table-striped">
					<tr>
						<th colspan="7">
							<%= "#{@date.strftime('%B')} #{@date.year}" %>
						</th>
					</tr>
					<%= calendar @date do |date| %>
						<%= date.day %>
						<%# if @events_by_date[date] %>
							<!-- <ul> -->
								<%# @events_by_date[date].each do |event| %>
									<!-- <li><%#= link_to event.name, event %></li> -->
								<%# end %>
							<!-- </ul> -->
						<%# end %>
					<% end %>
				</table>
				<nav class="down1x agenda">
					<a href="#" data-toggle="modal" data-target="#myModal"><b>24 May 2015</b></a>
					&nbsp;<i>Sampulkreativ Launching</i>
				</nav>
			</article>
		</section>
		<br>
		<nav class="clearfix"></nav>
		<section class="sidebarside">
			<article>
				<nav><b>Tags</b></nav>
				<a href="javascript:void(0)"><nav class="category"><span>GALLERY</span></nav></a>
				<a href="javascript:void(0)"><nav class="category"><span>LINKS</span></nav></a>
				<a href="javascript:void(0)"><nav class="category"><span>QOUTE</span></nav></a>
				<a href="javascript:void(0)"><nav class="category"><span>VIDEOS</span></nav></a>
				<nav class="clearfix"></nav>
			</article>
		</section>
		<nav class="clearfix"></nav>
	</div>			
<!-- END MAIN RIGHT SIDEBAR -->
<script>
	jQuery(document).ready(function() {
	    jQuery('.tabs .tab-links a').on('click', function(e)  {
	        var currentAttrValue = jQuery(this).attr('href');
	 
	        // Show/Hide Tabs
	        jQuery('.tabs ' + currentAttrValue).show().siblings().hide();
	 
	        jQuery(currentAttrValue+"_acticle").addClass('active').siblings().removeClass('active');
	        e.preventDefault();
	    });
	});
</script>

app/views/dashboard/shared/_sidebar_menu.html.erb
<div id="sidebar">
          <div class="clear"></div>
          <div class="sidebar-box">
            <h3>Categories</h3>
            <ul>
            <% @categories_list.each do |category| %>
                    <li class="cat-item">
                          <%= link_to "#{category.name}", dashboard_home_show_categories_path(category) %>
                    </li>
                    <ul class="sub_side_menu">
                    <% category.sub_categories.each do |sub_category| %>
                          <li><%= link_to sub_category.name, dashboard_home_show_sub_categories_path(sub_category) %></li>
                     <% end %>
                    </ul>
            <% end %>
            </ul>
          </div>
          <div class="sidebar-box">
            <h3>Recent Posts</h3>
            <ul>
            <% @recent_posts.each do |article| %>
                  <li><%= link_to article.title, dashboard_home_path(article) %></li>
            <% end %>
            </ul>
          </div>
          <div class="sidebar-box">
            <h3>Galleries</h3>
            <ul>
              <% @galleries.each do |gallery| %>
                  <li><%= link_to gallery.name, dashboard_gallery_path(gallery) %></li>
              <% end %>
            </ul>
          </div>
        </div>
</div>
        <div class="clear"></div>